import { useEffect, useState } from 'react';
import { Link, useNavigate } from '../router';
import { deleteTrade, getMyTrades, updateTrade } from '../api/tradeApi';
import TradeEditModal from '../components/TradeEditModal';
import ToyArt from '../components/ToyArt';

export default function MyPage() {
  const userId = localStorage.getItem('userId'); const nickname = localStorage.getItem('nickname'); const navigate = useNavigate(); const [tab, setTab] = useState('posts'); const [trades, setTrades] = useState([]); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  const load = () => getMyTrades(userId).then(setTrades).catch((err) => { setTrades([]); setError(err.message); });
  useEffect(() => { load(); }, [userId]);
  const remove = async (trade) => { if (!window.confirm(`'${trade.mallang.name}' 게시글을 삭제할까요?`)) return; try { await deleteTrade(trade.id, userId); setTrades((items) => items.filter((item) => item.id !== trade.id)); } catch (err) { setError(err.message); } };
  return <main className="my"><section className="my-hero"><span className="profile big">{nickname?.slice(0, 1) ?? '몽'}</span><div><p className="eyebrow">MY MALLANG</p><h1>{nickname}님, 안녕하세요!</h1><p>내 말랑이 활동을 관리해 보세요.</p></div></section><div className="my-layout"><aside className="my-menu"><button className={tab === 'profile' ? 'active' : ''} onClick={() => setTab('profile')}>내 정보</button><button className={tab === 'posts' ? 'active' : ''} onClick={() => setTab('posts')}>게시글 <b>{trades.length}</b></button><button onClick={() => navigate('/chats')}>교환 채팅</button><button className={tab === 'status' ? 'active' : ''} onClick={() => setTab('status')}>거래 상태</button></aside><section className="my-content">{tab === 'profile' && <><p className="eyebrow">MY PROFILE</p><h2>내 정보</h2><div className="profile-panel"><b>닉네임</b><span>{nickname}</span><b>회원 번호</b><span>{userId}</span></div></>}{tab === 'status' && <><p className="eyebrow">TRADE STATUS</p><h2>거래 상태</h2><div className="status-summary"><span>모집중 <b>{trades.filter((trade) => trade.status === '모집중').length}</b></span><span>거래중 <b>{trades.filter((trade) => trade.status === '거래중').length}</b></span><span>거래완료 <b>{trades.filter((trade) => trade.status === '거래완료').length}</b></span></div></>}{tab === 'posts' && <><div className="my-section-head"><div><p className="eyebrow">MY EXCHANGE POSTS</p><h2>내가 작성한 게시글</h2></div><Link className="primary" to="/trades">교환 글 쓰기</Link></div>{error && <p className="trade-error">{error}</p>}{trades.length === 0 ? <p className="trade-empty">작성한 교환 게시글이 없습니다.</p> : <div className="my-trade-grid">{trades.map((trade) => <article className="my-trade-card" key={trade.id}><ToyArt mallang={trade.mallang} /><div><span className={`status ${trade.status === '거래중' ? 'muted' : ''}`}>{trade.status}</span><h3>{trade.mallang.name}</h3><p>원하는 말랑이 · {trade.wanted}</p><p>📍 {trade.location}</p><small>{trade.createdAt}</small><div className="manage-actions"><Link to={`/trades/${trade.id}`}>상세 보기</Link><button onClick={() => setEditing(trade)}>수정</button><button className="delete" onClick={() => remove(trade)}>삭제</button></div></div></article>)}</div>}</>}</section></div>{editing && <TradeEditModal trade={editing} onClose={() => setEditing(null)} onSave={async (payload) => { try { const updated = await updateTrade(editing.id, { ...payload, user_id: userId }); setTrades((items) => items.map((item) => item.id === updated.id ? updated : item)); setEditing(null); } catch (err) { setError(err.message); } }} />}</main>;
}
